services:
  - type: web
    name: excel-merge-pro
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app_v2:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
